# Servidor y Nombre
server.port=9090
spring.application.name=customers-prod
custom.log.message=Ejecutando en PROD

spring.datasource.url=jdbc:h2:file:/data/proddb;DB_CLOSE_DELAY=-1

# Consola H2 (Desactivada por seguridad)
spring.h2.console.enabled=false

# Logs de SQL (Desactivados)
spring.jpa.show-sql=false