# --- Configuracion General de H2 ---
spring.datasource.url=jdbc:h2:mem:customerdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# --- Seguridad y Puerto ---
server.port=${PORT:8080}
# Credenciales dinamicas (Inyectadas en ejecucion)
spring.datasource.username=''
spring.datasource.password=''

# --- Estrategia de creacion de tablas ---
spring.jpa.hibernate.ddl-auto=update

# --- Docker Compose ---
spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=start-and-stop

# --- CONFIGURACION DE SWAGGER / OPENAPI 3 ---
# Ruta para acceder al UI (e.g., http://localhost:8080/swagger-ui.html)
springdoc.swagger-ui.path=/swagger-ui.html
# Ruta para el JSON de la definicion de la API
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=project_users.infrastructure.rest

# --- Logs Personalizados ---
custom.log.message=Aplicacion de usuarios iniciada correctamente