# Configuración General de H2
spring.datasource.url=jdbc:h2:mem:customerdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Seguridad: Credenciales dinámicas (Inyectadas en ejecución)
# Sintaxis: ${VARIABLE_ENTORNO:VALOR_POR_DEFECTO}
spring.datasource.username=''
spring.datasource.password=''

# Estrategia de creación de tablas
spring.jpa.hibernate.ddl-auto=update