# Configuracion General de H2
spring.datasource.url=jdbc:h2:mem:customerdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

server.port=${PORT:8080}

# Seguridad: Credenciales dinamicas (Inyectadas en ejecucion)
spring.datasource.username=''
spring.datasource.password=''

# Estrategia de creacion de tablas
spring.jpa.hibernate.ddl-auto=update

#DockerCompose
spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=start-and-stop

custom.log.message=Aplicacion de usuarios iniciada correctamente