name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          # Actualizamos la ruta de la caché para que coincida con la estructura real
          key: ${{ runner.os }}-m2-${{ hashFiles('users/users/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Usamos -f (file) para apuntar a la ruta profunda del pom.xml
        run: >
          mvn -B -f users/users/pom.xml
          org.jacoco:jacoco-maven-plugin:prepare-agent 
          verify 
          org.jacoco:jacoco-maven-plugin:report 
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar 
          -Dsonar.projectKey=rafaelgarciaa_Pr-rg-users